// Food data for the guided flow, one entry per meal.
// Each row is a category (e.g. "Boisson"); each option belongs to a color
// variant defined in src/input.css (.food-card-<color>, .card-badge-<color>).
// The first 4 options per row come from the original hospital guide; the
// next 4 extend the choice using the same guide's equivalence tables
// (féculents, fruits) where available, or a consistent extra option
// otherwise. `tip` is a short preparation idea shown on the summary screen.
const MEALS = {
  p1: {
    label: 'Petit-Déjeuner',
    emoji: '🍳',
    rows: [
      { id: 'p1-1', label: 'Boisson', warning: "Bien s'hydrater dès le matin aide à démarrer la journée en douceur.", options: [
        { color: 'amber',   icon: '☕',   title: 'Café noir / Allongé', name: 'Café noir / Allongé', note: 'Sans sucre', tip: 'Torréfaction douce, à savourer sans sucre pour préserver le goût.' },
        { color: 'emerald', icon: '🍵',   title: 'Thé vert ou noir', name: 'Thé vert ou noir', note: 'Sans sucre', tip: 'Laissez infuser 3 min pour un thé vert, 5 min pour un thé noir.' },
        { color: 'pink',    icon: '🫖',   title: 'Thé / Tisane', name: 'Thé / Tisane citron menthe', note: 'Citron & Menthe', tip: 'Infusez avec une rondelle de citron frais et quelques feuilles de menthe.' },
        { color: 'sky',     icon: '☕🥛', title: 'Café au lait', name: 'Café au lait', note: 'Lait demi-écrémé', tip: 'Chauffez le lait sans le faire bouillir pour une mousse plus onctueuse.' },
        { color: 'purple',  icon: '☕',   title: 'Chicorée', name: 'Chicorée', note: 'Sans caféine', tip: 'Diluez 1 c.à.café de chicorée dans l\'eau chaude, sans sucre.' },
        { color: 'indigo',  icon: '🌿',   title: 'Tilleul-Camomille', name: 'Infusion Tilleul-Camomille', note: 'Apaisante, sans sucre', tip: 'Infusez 5-7 min, idéal pour démarrer la journée en douceur.' },
        { color: 'lime',    icon: '🍵',   title: 'Thé noir nature', name: 'Thé noir nature', note: 'Sans sucre', tip: 'Infusez 3-5 min selon l\'intensité souhaitée.' },
        { color: 'rose',    icon: '🥛',   title: 'Lait chaud nature', name: 'Lait chaud nature', note: 'Demi-écrémé', tip: 'Chauffez doucement sans faire bouillir, pour préserver les protéines.' },
      ]},
      { id: 'p1-2', label: 'Féculent', warning: 'Le féculent du petit-déjeuner apporte une énergie essentielle et évite les fringales avant midi.', options: [
        { color: 'amber',   icon: '🍞', title: 'Pain complet / Seigle', name: 'Pain complet (50-60g)', badge: '50-60g (2-3 tr.)', tip: 'Toastez légèrement pour plus de croustillant.' },
        { color: 'emerald', icon: '🥣', title: "Flocons d'avoine", name: "Flocons d'avoine (30-40g)", badge: '30-40g (3-4 c.à.s)', tip: 'Faites-les gonfler dans du lait chaud ou un yaourt pour un porridge minute.' },
        { color: 'pink',    icon: '🥞', title: '2 Pancakes maison', name: '2 Pancakes maison', badge: 'Farine complète', tip: 'Utilisez de la farine complète et cuisez sans matière grasse ajoutée.' },
        { color: 'sky',     icon: '🥖', title: 'Pain aux céréales', name: 'Pain aux céréales (50g)', badge: '50g (2 tranches)', tip: 'Idéal légèrement toasté avec une fine couche de matière grasse.' },
        { color: 'purple',  icon: '🍘', title: 'Biscottes ou Cracottes', name: 'Biscottes ou Cracottes', badge: '3-4 biscottes / 4 cracottes', tip: 'Simples et pratiques, à tartiner directement.' },
        { color: 'indigo',  icon: '🍞', title: 'Pain de mie complet', name: 'Pain de mie complet', badge: '2 petites tranches', tip: 'Préférez la version complète, plus riche en fibres.' },
        { color: 'lime',    icon: '🥣', title: 'Muesli complet', name: 'Muesli complet (30g)', badge: '30g (3 c.à.s)', tip: 'Mélangez à un yaourt nature ou du lait demi-écrémé.' },
        { color: 'rose',    icon: '🍘', title: 'Galettes de riz complet', name: 'Galettes de riz complet', badge: '3-4 galettes', tip: 'Craquantes, à tartiner comme du pain.' },
      ]},
      { id: 'p1-3', label: 'Tartine', warning: "Un peu de matière grasse ou de protéines ralentit l'absorption des sucres du petit-déjeuner.", options: [
        { color: 'amber',   icon: '🧈', title: 'Beurre', name: 'Beurre doux/demi-sel (10g)', note: '10g (1 noisette)', tip: 'Étalez-le à température ambiante pour une fine couche uniforme.' },
        { color: 'emerald', icon: '🥜', title: 'Beurre de cacahuète', name: "Purée d'amande / cacahuète", note: '1 c.à.café (100% pur)', tip: 'Choisissez une purée 100% pur fruit, sans huile de palme ajoutée.' },
        { color: 'pink',    icon: '🍯', title: 'Miel ou Confiture', name: 'Miel ou Confiture (1 c.à.c)', note: '1 c.à.café rase max', tip: 'Une fine couche suffit : privilégiez une confiture allégée en sucre.' },
        { color: 'sky',     icon: '🥑', title: 'Avocat écrasé', name: 'Avocat écrasé (1/4)', note: "1/4 d'avocat", tip: 'Écrasez à la fourchette avec un filet de citron et un peu de poivre.' },
        { color: 'purple',  icon: '🧀', title: 'Fromage frais léger', name: 'Fromage frais léger (< 20% MG)', note: '< 20% MG', tip: "Étalez directement sur le pain, agrémenté d'herbes fraîches." },
        { color: 'indigo',  icon: '🍏', title: 'Compote sans sucre', name: 'Compote sans sucre (en tartine)', note: 'En tartine', tip: 'Une alternative douce et sans sucre ajouté au miel ou à la confiture.' },
        { color: 'lime',    icon: '🌰', title: 'Purée de sésame (tahin)', name: 'Purée de sésame (tahin)', note: '1 c.à.café', tip: 'Une fine couche apporte du croquant et des bons acides gras.' },
        { color: 'rose',    icon: '🥛', title: 'Ricotta allégée', name: 'Ricotta allégée', note: 'Légère', tip: "Mélangez avec un peu de poivre ou d'herbes pour plus de goût." },
      ]},
      { id: 'p1-4', label: 'Protéines', warning: "Il est essentiel d'avoir un apport en protéines pour la satiété et l'équilibre glycémique.", options: [
        { color: 'amber',   icon: '🥛', title: 'Yaourt nature', name: 'Yaourt nature / Fromage blanc', note: 'Ou Fromage blanc 2%', tip: "Nature et sans sucre, à agrémenter d'une pincée de cannelle si besoin." },
        { color: 'emerald', icon: '🥛', title: 'Lait demi-écrémé', name: 'Lait demi-écrémé (150ml)', note: '150ml (chaud/froid)', tip: 'À boire chaud ou froid, seul ou avec un café.' },
        { color: 'pink',    icon: '🥣', title: 'Skyr / Petit suisse', name: 'Skyr ou Petit suisse', note: 'Riche en protéines', tip: 'Très riche en protéines, idéal pour la satiété du matin.' },
        { color: 'sky',     icon: '🍳', title: '1 Œuf ou Jambon', name: '1 Œuf au plat ou Jambon', note: 'Œuf coque/plat / 1 tr.', tip: "Cuisez l'œuf à la coque ou au plat sans matière grasse ajoutée." },
        { color: 'purple',  icon: '🥣', title: 'Fromage blanc 0%', name: 'Fromage blanc 0%', note: 'Riche en protéines', tip: 'Mélangez avec quelques fruits frais coupés en dés.' },
        { color: 'indigo',  icon: '🍗', title: 'Blanc de dinde/poulet', name: 'Blanc de dinde ou poulet (1 tranche)', note: '1 tranche', tip: 'Une tranche fine, simple et rapide à intégrer au petit-déjeuner.' },
        { color: 'lime',    icon: '🥛', title: 'Kéfir nature', name: 'Kéfir nature', note: 'Probiotique naturel', tip: 'Riche en probiotiques, à consommer frais.' },
        { color: 'rose',    icon: '🧀', title: 'Cottage cheese', name: 'Cottage cheese', note: 'Riche en protéines', tip: 'Texture granuleuse, à tartiner ou déguster à la cuillère.' },
      ]},
      { id: 'p1-5', label: 'Fruit frais', warning: 'Le fruit apporte des fibres et des vitamines essentielles à votre équilibre.', options: [
        { color: 'amber',   icon: '🍎', title: '1 Pomme moyenne', name: '1 Pomme avec la peau', note: 'Conserver la peau', tip: 'Conservez la peau pour profiter de toutes ses fibres.' },
        { color: 'emerald', icon: '🫐', title: 'Myrtilles / Fraises', name: 'Myrtilles / Fraises (100g)', note: '1 poignée (100g)', tip: 'Rincez-les juste avant de les consommer pour préserver leur fraîcheur.' },
        { color: 'pink',    icon: '🥝', title: '1 Kiwi frais', name: '1 Kiwi frais', note: 'Riche en vitamine C', tip: 'Coupez-le en deux et dégustez-le à la cuillère.' },
        { color: 'sky',     icon: '🍊', title: '2 Clémentines', name: '2 Clémentines / Pamplemousse', note: 'Ou 1/2 pamplemousse', tip: 'Faciles à peler, idéales à emporter.' },
        { color: 'purple',  icon: '🍊', title: '1 Orange', name: '1 Orange', note: 'Riche en vitamine C', tip: 'Pressée ou en quartiers, à consommer entière pour garder les fibres.' },
        { color: 'indigo',  icon: '🍐', title: '1 Poire', name: '1 Poire', note: 'Fraîche & croquante', tip: 'Choisissez-la bien mûre pour plus de saveur.' },
        { color: 'lime',    icon: '🍌', title: '1/2 Banane', name: '1/2 Banane (100g)', note: 'Pas trop mûre', tip: 'Coupez-la en rondelles sur un yaourt ou un porridge.' },
        { color: 'rose',    icon: '🍑', title: 'Abricots ou Prunes', name: '3-4 Abricots ou Prunes', note: 'Frais de saison', tip: 'À déguster frais et bien mûrs, en pleine saison.' },
      ]},
    ],
  },
  p2: {
    label: 'Déjeuner',
    emoji: '🍽️',
    rows: [
      { id: 'p2-1', label: 'Crudités', warning: "Les légumes crus apportent des fibres qui ralentissent l'absorption des glucides du repas.", options: [
        { color: 'amber',   icon: '🍅', title: 'Tomates en salade', name: "Tomates fraîches + Huile d'olive", note: "1 c.à.c huile d'olive", tip: "Coupez-les en quartiers, assaisonnez d'un filet d'huile d'olive." },
        { color: 'sky',     icon: '🥕', title: 'Carottes râpées', name: 'Carottes râpées citron & colza', note: 'Citron & Huile colza', tip: "Râpez-les finement, assaisonnez de citron et d'huile de colza." },
        { color: 'emerald', icon: '🥒', title: 'Concombre tzatziki', name: 'Concombre au yaourt & aneth', note: 'Yaourt, aneth, menthe', tip: "Mélangez concombre, yaourt nature, aneth et une pointe d'ail." },
        { color: 'purple',  icon: '🥣', title: 'Soupe de légumes', name: 'Potage légumes (sans p.d.t)', note: 'Sans p.d.t (200ml)', tip: 'Mixez des légumes variés sans pomme de terre pour rester léger.' },
        { color: 'pink',    icon: '🥬', title: 'Salade verte vinaigrette', name: 'Salade verte vinaigrette', note: 'Huile de colza', tip: "Assaisonnez d'une vinaigrette légère à l'huile de colza." },
        { color: 'indigo',  icon: '🥗', title: 'Betteraves nature', name: 'Betteraves nature', note: 'Cuites vapeur', tip: 'Cuites vapeur, coupées en dés, sans matière grasse ajoutée.' },
        { color: 'lime',    icon: '🥬', title: 'Radis croquants', name: 'Radis croquants', note: 'Croquants nature', tip: 'Servez-les nature, avec un peu de sel ou de fromage frais léger.' },
        { color: 'rose',    icon: '🥗', title: 'Céleri rémoulade allégée', name: 'Céleri rémoulade allégée', note: 'Mayonnaise allégée', tip: 'Préparez avec une mayonnaise allégée et un filet de citron.' },
      ]},
      { id: 'p2-2', label: 'Protéine', warning: "Il est essentiel d'avoir un apport en protéines à chaque repas.", options: [
        { color: 'amber',   icon: '🍗', title: 'Escalope de poulet', name: 'Escalope de poulet grillée (100g)', badge: '100-120g grillé', tip: "Grillez-la à la poêle avec un filet d'huile d'olive et des herbes." },
        { color: 'sky',     icon: '🐟', title: 'Pavé de saumon', name: 'Pavé de saumon au four (110g)', badge: '110g papillote', tip: 'Cuisson en papillote pour préserver moelleux et oméga-3.' },
        { color: 'emerald', icon: '🍳', title: '2 Œufs au plat', name: '2 Œufs au plat / poêlés', badge: 'Cuits peu de gras', tip: 'Cuisez-les dans une poêle antiadhésive, sans excès de matière grasse.' },
        { color: 'purple',  icon: '🥩', title: 'Steak haché 5%', name: 'Steak haché 5% poêlé (100g)', badge: '100g grillé', tip: 'Poêlez-le rapidement à feu vif pour le garder tendre.' },
        { color: 'pink',    icon: '🍗', title: 'Escalope de dinde', name: 'Escalope de dinde (100g)', badge: '100g grillée', tip: 'Grillez avec des herbes de Provence pour plus de saveur.' },
        { color: 'indigo',  icon: '🐟', title: 'Thon au naturel', name: 'Thon au naturel (100g)', badge: '100g égoutté', tip: 'Égouttez bien avant de l\'incorporer à une salade.' },
        { color: 'lime',    icon: '🦐', title: 'Crevettes décortiquées', name: 'Crevettes décortiquées (100g)', badge: '100g cuites', tip: "Poêlez rapidement à feu vif avec de l'ail et du persil." },
        { color: 'rose',    icon: '🍖', title: 'Jambon blanc dégraissé', name: 'Jambon blanc dégraissé (2 tranches)', badge: '2 tranches', tip: 'Retirez le gras visible avant de le consommer.' },
      ]},
      { id: 'p2-3', label: 'Féculent', warning: "Le féculent est indispensable pour l'énergie et la satiété du déjeuner.", options: [
        { color: 'amber',   icon: '🍝', title: 'Pâtes complètes', name: 'Pâtes complètes (100-120g)', badge: '100-120g cuites', tip: 'Cuisson al dente pour un index glycémique plus favorable.' },
        { color: 'sky',     icon: '🍚', title: 'Riz basmati / complet', name: 'Riz basmati / complet (100g)', badge: '100g (3 c.à.s)', tip: 'Rincez-le avant cuisson pour un riz plus léger.' },
        { color: 'emerald', icon: '🫘', title: 'Lentilles vertes', name: 'Lentilles vertes (120g)', badge: '120g (4 c.à.s)', tip: 'Cuisez-les sans trempage préalable, elles cuisent vite.' },
        { color: 'purple',  icon: '🥔', title: 'Pommes de terre', name: '2 Pommes de terre vapeur (120g)', badge: '2 petites (120g)', tip: 'Cuisson vapeur pour préserver leurs nutriments.' },
        { color: 'pink',    icon: '🍚', title: 'Semoule ou Quinoa', name: 'Semoule ou Quinoa (70g)', badge: '70g cuits', tip: 'Rincez le quinoa avant cuisson pour retirer son amertume.' },
        { color: 'indigo',  icon: '🍞', title: 'Pain', name: 'Pain (40g)', badge: '40g', tip: 'Choisissez une variété complète ou aux céréales.' },
        { color: 'lime',    icon: '🫛', title: 'Petits pois', name: 'Petits pois (150g)', badge: '150g (8 c.à.s)', tip: 'Cuisson vapeur rapide pour garder leur croquant.' },
        { color: 'rose',    icon: '🍕', title: 'Part de Pizza ou Quiche', name: 'Part de Pizza ou Quiche (100g)', badge: '100g', tip: 'Privilégiez une version maison, moins grasse et salée.' },
      ]},
      { id: 'p2-4', label: 'Légumes cuits', warning: "Les légumes à volonté aident à réguler l'appétit et la glycémie.", options: [
        { color: 'amber',   icon: '🥦', title: 'Brocolis vapeur', name: "Brocolis vapeur + Huile d'olive", note: "Filet d'huile d'olive", tip: 'Cuisson vapeur courte pour garder couleur et vitamines.' },
        { color: 'sky',     icon: '🫛', title: 'Haricots verts', name: 'Haricots verts persillade', note: 'Persil & Ail', tip: "Poêlez-les avec de l'ail et du persil après cuisson vapeur." },
        { color: 'emerald', icon: '🍆', title: 'Ratatouille maison', name: 'Ratatouille maison', note: 'Courgettes & Poivrons', tip: 'Mijotez courgettes, aubergines et poivrons à feu doux.' },
        { color: 'purple',  icon: '🥬', title: 'Épinards crème', name: 'Épinards à la crème 15%', note: 'Crème légère 15%', tip: 'Utilisez une crème légère à 15% de matière grasse.' },
        { color: 'pink',    icon: '🥬', title: 'Poireaux vinaigrette', name: 'Poireaux vinaigrette', note: "Huile d'olive", tip: 'Cuisson vapeur, servis froids avec une vinaigrette légère.' },
        { color: 'indigo',  icon: '🥬', title: 'Épinards nature', name: 'Épinards nature', note: 'Vapeur', tip: 'Cuisson rapide à la poêle, sans excès de matière grasse.' },
        { color: 'lime',    icon: '🥒', title: 'Courgettes sautées', name: 'Courgettes sautées', note: "Filet d'huile d'olive", tip: "Poêlez en fines lamelles avec un filet d'huile d'olive." },
        { color: 'rose',    icon: '🥦', title: 'Chou-fleur gratiné léger', name: 'Chou-fleur gratiné léger', note: 'Béchamel légère', tip: 'Utilisez une béchamel allégée en matière grasse.' },
      ]},
      { id: 'p2-5', label: 'Dessert', warning: "Le produit laitier ou le fruit en fin de repas complète l'équilibre glycémique du déjeuner.", options: [
        { color: 'amber',   icon: '🧀', title: 'Portion Fromage', name: 'Fromage (30g) + pain', note: '30g + 1 bout de pain', tip: "Accompagnez d'un petit bout de pain complet." },
        { color: 'sky',     icon: '🍍', title: 'Ananas frais', name: '2 Tranches ananas frais', note: '2 tranches fines', tip: 'Coupez en tranches fines, à déguster nature.' },
        { color: 'emerald', icon: '🥣', title: 'Fromage blanc 2%', name: 'Fromage blanc 2% sans sucre', note: '100g sans sucre', tip: 'Sans sucre ajouté, éventuellement avec une pointe de vanille.' },
        { color: 'purple',  icon: '🍐', title: '1 Poire mûre', name: '1 Poire bien mûre', note: 'Riche en eau', tip: 'Choisissez-la bien mûre pour plus de douceur naturelle.' },
        { color: 'pink',    icon: '🥛', title: 'Yaourt nature', name: 'Yaourt nature', note: 'Édulcorant si besoin', tip: 'Ajoutez un édulcorant si besoin, sans sucre ajouté.' },
        { color: 'indigo',  icon: '🍏', title: 'Compote sans sucre', name: 'Compote sans sucre ajouté', note: 'Sans sucre ajouté', tip: "Vérifiez l'étiquette : sans sucres ajoutés." },
        { color: 'lime',    icon: '🥝', title: '1 Kiwi frais', name: '1 Kiwi frais', note: 'Riche en vitamine C', tip: 'Coupez-le en deux, à déguster à la cuillère.' },
        { color: 'rose',    icon: '🥣', title: 'Petit-suisse nature', name: 'Petit-suisse nature', note: 'Nature non sucré', tip: 'Nature et non sucré, simple et rapide.' },
      ]},
    ],
  },
  p3: {
    label: 'Goûter',
    emoji: '🍎',
    rows: [
      { id: 'p3-1', label: 'Boisson', warning: "Pensez à vous hydrater, même sans avoir soif.", options: [
        { color: 'amber',   icon: '🍵', title: 'Thé vert ou Tisane', name: 'Thé vert ou Tisane', note: 'Sans sucre ajouté', tip: 'Infusez sans sucre, à température de votre choix.' },
        { color: 'pink',    icon: '🍋', title: 'Eau citronnée', name: 'Eau au citron pressé', note: '250ml rafraîchissant', tip: "Pressez un demi-citron dans un grand verre d'eau fraîche." },
        { color: 'emerald', icon: '☕', title: 'Décaféiné', name: 'Café décaféiné', note: 'Sans sucre', tip: 'Idéal en fin de journée pour ne pas perturber le sommeil.' },
        { color: 'indigo',  icon: '🌿', title: 'Infusion Verveine', name: 'Infusion verveine', note: 'Apaisante sans sucre', tip: "Infusez 5 min pour une boisson apaisante en fin d'après-midi." },
        { color: 'sky',     icon: '🌿', title: 'Tisane camomille', name: 'Tisane camomille', note: 'Apaisante, sans sucre', tip: 'Infusez 5-7 min, idéale pour une pause détente.' },
        { color: 'purple',  icon: '☕', title: 'Chicorée', name: 'Chicorée', note: 'Sans caféine', tip: "Sans caféine, à diluer dans de l'eau chaude." },
        { color: 'lime',    icon: '💧', title: 'Eau plate', name: 'Eau plate', note: '250ml', tip: 'La boisson la plus simple pour bien vous hydrater.' },
        { color: 'rose',    icon: '🍵', title: 'Thé noir nature', name: 'Thé noir nature', note: 'Sans sucre', tip: 'Infusez 3-5 min selon le goût souhaité.' },
      ]},
      { id: 'p3-2', label: 'Fruit / Base', warning: 'Ne consommez jamais un fruit seul : associez-le à une protéine ou un féculent.', options: [
        { color: 'amber',   icon: '🍎', title: '1 Pomme ou Poire', name: '1 Pomme ou 1 Poire', note: 'Fraîche & croquante', tip: 'À croquer telle quelle, avec la peau si possible.' },
        { color: 'pink',    icon: '🍓', title: 'Fruits rouges', name: 'Fruits rouges (1 poignée)', note: '1 poignée (100g)', tip: 'Rincez-les juste avant de les consommer.' },
        { color: 'emerald', icon: '🍞', title: 'Pain complet', name: '1 Tranche pain complet (30g)', note: '1 tranche (30g)', tip: 'Une seule tranche suffit, à associer à une protéine.' },
        { color: 'indigo',  icon: '🍌', title: '1/2 Banane', name: '1/2 Banane', note: 'Pas trop mûre', tip: 'Choisissez-la pas trop mûre pour un index glycémique plus bas.' },
        { color: 'sky',     icon: '🍊', title: '1 Orange', name: '1 Orange', note: 'Riche en vitamine C', tip: 'En quartiers ou pressée, à consommer avec sa pulpe.' },
        { color: 'purple',  icon: '🥝', title: '2 Kiwis', name: '2 Kiwis', note: 'Riches en fibres', tip: 'Coupez-les en deux et dégustez à la cuillère.' },
        { color: 'lime',    icon: '🍊', title: '2 Clémentines', name: '2 Clémentines', note: 'Faciles à emporter', tip: 'Faciles à peler, parfaites pour une collation rapide.' },
        { color: 'rose',    icon: '🍑', title: '1 Pêche ou Nectarine', name: '1 Pêche ou Nectarine', note: 'Fruit de saison', tip: 'À déguster fraîche, en pleine saison.' },
      ]},
      { id: 'p3-3', label: 'Modérateur', warning: 'Les bonnes graisses et protéines lissent la glycémie et évitent le coup de barre.', options: [
        { color: 'amber',   icon: '🥜', title: 'Amandes ou Noix', name: 'Amandes / Noix non salées (15g)', badge: '15-20g (1 poignée)', tip: 'Une petite poignée non salée suffit.' },
        { color: 'pink',    icon: '🥣', title: 'Yaourt grec nature', name: 'Yaourt grec nature (1 pot)', badge: '1 pot (125g)', tip: 'Riche et onctueux, sans sucre ajouté.' },
        { color: 'emerald', icon: '🧀', title: 'Portion de Comté', name: 'Comté / Cantal (30g)', badge: '30g de fromage', tip: "30g suffisent, à associer à un fruit ou une tranche de pain." },
        { color: 'indigo',  icon: '🍫', title: 'Chocolat noir 70%+', name: '2 Carrés choc. noir 70% + noisettes', badge: '2 carrés + 4 noisettes', tip: '2 carrés suffisent pour une touche gourmande sans excès.' },
        { color: 'sky',     icon: '🥜', title: 'Noix de cajou non salées', name: 'Noix de cajou non salées (20g)', badge: '20g (1 poignée)', tip: 'Une petite poignée (20g) pour un encas rassasiant.' },
        { color: 'purple',  icon: '🥣', title: 'Fromage blanc 2% + amandes', name: 'Fromage blanc 2% + amandes', badge: '100g + 5 amandes', tip: 'Mélangez pour associer protéines et bonnes graisses.' },
        { color: 'lime',    icon: '🥣', title: 'Petit-suisse nature', name: 'Petit-suisse nature (x2)', badge: '2 pots (100g)', tip: 'Simple et pratique, sans sucre ajouté.' },
        { color: 'rose',    icon: '🍫', title: 'Chocolat noir 80%', name: 'Carré de chocolat noir 80%', badge: '1 carré', tip: 'Un seul carré suffit pour une note gourmande.' },
      ]},
    ],
  },
  p4: {
    label: 'Dîner',
    emoji: '🌙',
    rows: [
      { id: 'p4-1', label: 'Légumes', warning: 'Les légumes à volonté favorisent un dîner léger et rassasiant.', options: [
        { color: 'amber',   icon: '🥣', title: 'Soupe maison', name: 'Soupe poireaux/courgettes', note: 'Poireaux & courgettes (1 bol)', tip: 'Mixez poireaux et courgettes avec un bouillon léger.' },
        { color: 'sky',     icon: '🫑', title: 'Poivrons poêlés', name: 'Poivrons & courgettes poêlés', note: "Sautés à l'huile d'olive", tip: "Poêlez avec un filet d'huile d'olive et un peu d'ail." },
        { color: 'emerald', icon: '🥗', title: 'Salade fraîcheur', name: 'Salade composée (verte, radis)', note: 'Salade verte, radis, concombre', tip: 'Mélangez salade verte, radis et concombre avec une vinaigrette légère.' },
        { color: 'purple',  icon: '🥦', title: 'Chou-fleur vapeur', name: 'Chou-fleur & carottes vapeur', note: 'Et carottes tendres', tip: 'Cuisson vapeur avec des carottes pour plus de douceur.' },
        { color: 'pink',    icon: '🫛', title: 'Haricots verts vapeur', name: 'Haricots verts vapeur', note: 'Persillade légère', tip: "Terminez par une persillade légère à l'ail." },
        { color: 'indigo',  icon: '🍅', title: 'Tomates provençales', name: 'Tomates provençales', note: "Au four, sans excès d'huile", tip: "Passez-les au four avec un peu de chapelure et d'herbes." },
        { color: 'lime',    icon: '🥒', title: 'Courgettes vapeur', name: 'Courgettes vapeur', note: "Nature ou filet d'huile", tip: "Servez nature ou avec un filet d'huile d'olive." },
        { color: 'rose',    icon: '🥒', title: 'Concombre en salade', name: 'Concombre en salade', note: 'Yaourt & aneth', tip: 'Mélangez avec du yaourt nature et de l\'aneth.' },
      ]},
      { id: 'p4-2', label: 'Protéines', warning: "Une portion de protéines reste nécessaire, même le soir.", options: [
        { color: 'amber',   icon: '🍳', title: 'Omelette herbes', name: 'Omelette herbes (2 œufs)', badge: '2 œufs bio', tip: 'Battez les œufs avec des herbes fraîches, cuisson douce.' },
        { color: 'sky',     icon: '🐟', title: 'Dos de cabillaud', name: 'Dos de cabillaud / colin (120g)', badge: '120g vapeur', tip: 'Cuisson vapeur pour un poisson blanc léger et digeste.' },
        { color: 'emerald', icon: '🦪', title: 'Thon / Crevettes', name: 'Thon au naturel (80g) / Crevettes', badge: '80g égoutté', tip: 'Égouttez bien le thon avant de l\'incorporer à un plat.' },
        { color: 'purple',  icon: '🧆', title: 'Tofu mariné', name: 'Tofu poêlé mariné soja (100g)', badge: '100g sauté au soja', tip: 'Faites mariner dans un peu de sauce soja avant de poêler.' },
        { color: 'pink',    icon: '🍗', title: 'Blanc de poulet froid', name: 'Blanc de poulet froid (100g)', badge: '100g', tip: 'Préparez à l\'avance pour un dîner rapide.' },
        { color: 'indigo',  icon: '🍖', title: 'Jambon blanc dégraissé', name: 'Jambon blanc dégraissé (1 tranche)', badge: '1 tranche', tip: 'Retirez le gras visible avant de servir.' },
        { color: 'lime',    icon: '🧆', title: 'Tofu nature', name: 'Tofu nature (100g)', badge: '100g', tip: 'Poêlez avec des épices pour plus de goût.' },
        { color: 'rose',    icon: '🥚', title: '1 Œuf dur', name: '1 Œuf dur', badge: '1 œuf', tip: 'Cuisson 9-10 min pour un jaune bien pris.' },
      ]},
      { id: 'p4-3', label: 'Féculent', warning: 'Un féculent modéré le soir aide à réguler la glycémie au réveil.', options: [
        { color: 'amber',   icon: '🍞', title: 'Pain complet', name: 'Pain complet (30-40g)', badge: '30-40g (1 tranche)', tip: 'Une portion modérée le soir, pour un apport en douceur.' },
        { color: 'sky',     icon: '🌾', title: 'Quinoa / Boulgour', name: 'Quinoa / Boulgour cuit (80-100g)', badge: '80-100g (2-3 c.à.s)', tip: 'Cuisson rapide, léger et digeste pour le soir.' },
        { color: 'emerald', icon: '🌽', title: 'Maïs / Pois chiches', name: 'Maïs ou Pois chiches (3 c.à.s)', badge: '3 c.à.soupe', tip: 'Rincez bien avant de les incorporer à un plat.' },
        { color: 'purple',  icon: '🍜', title: 'Nouilles Soba', name: 'Nouilles Soba sarrasin (80g)', badge: '80g (sarrasin)', tip: 'Cuisson rapide, à rincer à l\'eau froide après cuisson.' },
        { color: 'pink',    icon: '🍚', title: 'Riz complet', name: 'Riz complet (70g)', badge: '70g cuits', tip: 'Cuisson plus longue que le riz blanc, mais plus riche en fibres.' },
        { color: 'indigo',  icon: '🫘', title: 'Lentilles', name: 'Lentilles (100g)', badge: '100g', tip: 'Cuisson simple, sans trempage préalable.' },
        { color: 'lime',    icon: '🫛', title: 'Petits pois', name: 'Petits pois (100g)', badge: '100g', tip: 'Cuisson vapeur rapide pour garder leur texture.' },
        { color: 'rose',    icon: '🍘', title: 'Biscottes', name: 'Biscottes', badge: '2-3 biscottes', tip: 'Simples et légères pour accompagner le repas du soir.' },
      ]},
      { id: 'p4-4', label: 'Laitage', warning: 'Le laitage complète les apports en calcium et en protéines du dîner.', options: [
        { color: 'amber',   icon: '🥛', title: 'Yaourt nature', name: 'Yaourt nature (1 pot)', note: 'Sans sucre ajouté', tip: 'Sans sucre ajouté, simple et digeste avant le coucher.' },
        { color: 'sky',     icon: '🥣', title: 'Faisselle 0-3%', name: 'Faisselle ciboulette (1 pot)', note: 'Pincée de ciboulette', tip: 'Égouttez légèrement avant de parsemer de ciboulette.' },
        { color: 'emerald', icon: '🧀', title: 'Feta émiettée', name: 'Feta émiettée (20-30g)', note: '20-30g dans la salade', tip: 'Émiettez sur une salade pour plus de saveur avec modération.' },
        { color: 'purple',  icon: '🌱', title: 'Yaourt au Soja', name: 'Yaourt au soja nature', note: 'Enrichi en calcium', tip: 'Une alternative végétale enrichie en calcium.' },
        { color: 'pink',    icon: '🥛', title: 'Lait ribot', name: 'Lait ribot', note: 'Nature, sans sucre', tip: 'Nature et rafraîchissant, sans sucre ajouté.' },
        { color: 'indigo',  icon: '🥛', title: 'Kéfir nature', name: 'Kéfir nature', note: 'Probiotique naturel', tip: 'Riche en probiotiques, à consommer frais.' },
        { color: 'lime',    icon: '🥣', title: 'Fromage blanc 0%', name: 'Fromage blanc 0%', note: 'Sans sucre ajouté', tip: 'Simple et léger, sans sucre ajouté.' },
        { color: 'rose',    icon: '🧀', title: 'Mozzarella light', name: 'Mozzarella light (20g)', note: '20g', tip: 'Simple et léger, à parsemer sur une salade.' },
      ]},
      { id: 'p4-5', label: 'Fruit / Douceur', warning: 'Terminez la journée par un fruit ou une compote sans sucre ajouté.', options: [
        { color: 'amber',   icon: '🍏', title: 'Compote maison', name: 'Compote maison sans sucre', note: 'Sans sucre ajouté', tip: 'Préparez-la vous-même pour être sûr qu\'elle est sans sucre ajouté.' },
        { color: 'sky',     icon: '🍑', title: '1 Pêche / Nectarine', name: '1 Pêche ou Nectarine', note: 'Fruit frais de saison', tip: 'À déguster fraîche, en pleine saison.' },
        { color: 'emerald', icon: '🍊', title: '1 Orange fraîche', name: '1 Orange en quartiers', note: 'En quartiers', tip: 'En quartiers, pour terminer le repas en douceur.' },
        { color: 'purple',  icon: '🍈', title: 'Tranche de melon', name: '1 Tranche de melon (120g)', note: '120g rafraîchissant', tip: 'Choisissez-le bien mûr pour plus de saveur.' },
        { color: 'pink',    icon: '🍎', title: '1 Pomme', name: '1 Pomme', note: 'Avec la peau', tip: 'Avec la peau, pour profiter de ses fibres.' },
        { color: 'indigo',  icon: '🍐', title: '1 Poire', name: '1 Poire', note: 'Bien mûre', tip: 'Bien mûre, à déguster nature.' },
        { color: 'lime',    icon: '🍇', title: 'Raisin', name: '100g de Raisin', note: 'Une quinzaine de grains', tip: 'Rincez-le avant de le consommer, une quinzaine de grains suffit.' },
        { color: 'rose',    icon: '🍇', title: '2 Figues fraîches', name: '2 Figues fraîches (100g)', note: '100g', tip: 'À déguster fraîches, en pleine saison, coupées en deux.' },
      ]},
    ],
  },
};
