// Food data for the guided flow, one entry per meal.
// Each row is a category (e.g. "Boisson"); each option belongs to a color
// variant defined in src/input.css (.food-card-<color>, .card-badge-<color>).
// The first 4 options per row come from the original hospital guide; the
// next 4 extend the choice using the same guide's equivalence tables
// (féculents, fruits) where available, or a consistent extra option
// otherwise.
const MEALS = {
  p1: {
    label: 'Petit-Déjeuner',
    emoji: '🍳',
    rows: [
      { id: 'p1-1', label: 'Boisson', options: [
        { color: 'amber',   icon: '☕',   title: 'Café noir / Allongé', name: 'Café noir / Allongé', note: 'Sans sucre' },
        { color: 'emerald', icon: '🍵',   title: 'Thé vert ou noir', name: 'Thé vert ou noir', note: 'Sans sucre' },
        { color: 'pink',    icon: '🫖',   title: 'Thé / Tisane', name: 'Thé / Tisane citron menthe', note: 'Citron & Menthe' },
        { color: 'sky',     icon: '☕🥛', title: 'Café au lait', name: 'Café au lait', note: 'Lait demi-écrémé' },
        { color: 'purple',  icon: '☕',   title: 'Chicorée', name: 'Chicorée', note: 'Sans caféine' },
        { color: 'indigo',  icon: '🌿',   title: 'Tilleul-Camomille', name: 'Infusion Tilleul-Camomille', note: 'Apaisante, sans sucre' },
        { color: 'lime',    icon: '🍵',   title: 'Thé noir nature', name: 'Thé noir nature', note: 'Sans sucre' },
        { color: 'rose',    icon: '🥛',   title: 'Lait chaud nature', name: 'Lait chaud nature', note: 'Demi-écrémé' },
      ]},
      { id: 'p1-2', label: 'Féculent', options: [
        { color: 'amber',   icon: '🍞', title: 'Pain complet / Seigle', name: 'Pain complet (50-60g)', badge: '50-60g (2-3 tr.)' },
        { color: 'emerald', icon: '🥣', title: "Flocons d'avoine", name: "Flocons d'avoine (30-40g)", badge: '30-40g (3-4 c.à.s)' },
        { color: 'pink',    icon: '🥞', title: '2 Pancakes maison', name: '2 Pancakes maison', badge: 'Farine complète' },
        { color: 'sky',     icon: '🥖', title: 'Pain aux céréales', name: 'Pain aux céréales (50g)', badge: '50g (2 tranches)' },
        { color: 'purple',  icon: '🍘', title: 'Biscottes ou Cracottes', name: 'Biscottes ou Cracottes', badge: '3-4 biscottes / 4 cracottes' },
        { color: 'indigo',  icon: '🍞', title: 'Pain de mie complet', name: 'Pain de mie complet', badge: '2 petites tranches' },
        { color: 'lime',    icon: '🥣', title: 'Muesli complet', name: 'Muesli complet (30g)', badge: '30g (3 c.à.s)' },
        { color: 'rose',    icon: '🍘', title: 'Galettes de riz complet', name: 'Galettes de riz complet', badge: '3-4 galettes' },
      ]},
      { id: 'p1-3', label: 'Tartine', options: [
        { color: 'amber',   icon: '🧈', title: 'Beurre', name: 'Beurre doux/demi-sel (10g)', note: '10g (1 noisette)' },
        { color: 'emerald', icon: '🥜', title: 'Beurre de cacahuète', name: "Purée d'amande / cacahuète", note: '1 c.à.café (100% pur)' },
        { color: 'pink',    icon: '🍯', title: 'Miel ou Confiture', name: 'Miel ou Confiture (1 c.à.c)', note: '1 c.à.café rase max' },
        { color: 'sky',     icon: '🥑', title: 'Avocat écrasé', name: 'Avocat écrasé (1/4)', note: "1/4 d'avocat" },
        { color: 'purple',  icon: '🧀', title: 'Fromage frais léger', name: 'Fromage frais léger (< 20% MG)', note: '< 20% MG' },
        { color: 'indigo',  icon: '🍏', title: 'Compote sans sucre', name: 'Compote sans sucre (en tartine)', note: 'En tartine' },
        { color: 'lime',    icon: '🌰', title: 'Purée de sésame (tahin)', name: 'Purée de sésame (tahin)', note: '1 c.à.café' },
        { color: 'rose',    icon: '🥛', title: 'Ricotta allégée', name: 'Ricotta allégée', note: 'Légère' },
      ]},
      { id: 'p1-4', label: 'Protéines', options: [
        { color: 'amber',   icon: '🥛', title: 'Yaourt nature', name: 'Yaourt nature / Fromage blanc', note: 'Ou Fromage blanc 2%' },
        { color: 'emerald', icon: '🥛', title: 'Lait demi-écrémé', name: 'Lait demi-écrémé (150ml)', note: '150ml (chaud/froid)' },
        { color: 'pink',    icon: '🥣', title: 'Skyr / Petit suisse', name: 'Skyr ou Petit suisse', note: 'Riche en protéines' },
        { color: 'sky',     icon: '🍳', title: '1 Œuf ou Jambon', name: '1 Œuf au plat ou Jambon', note: 'Œuf coque/plat / 1 tr.' },
        { color: 'purple',  icon: '🥣', title: 'Fromage blanc 0%', name: 'Fromage blanc 0%', note: 'Riche en protéines' },
        { color: 'indigo',  icon: '🍗', title: 'Blanc de dinde/poulet', name: 'Blanc de dinde ou poulet (1 tranche)', note: '1 tranche' },
        { color: 'lime',    icon: '🥛', title: 'Kéfir nature', name: 'Kéfir nature', note: 'Probiotique naturel' },
        { color: 'rose',    icon: '🧀', title: 'Cottage cheese', name: 'Cottage cheese', note: 'Riche en protéines' },
      ]},
      { id: 'p1-5', label: 'Fruit frais', options: [
        { color: 'amber',   icon: '🍎', title: '1 Pomme moyenne', name: '1 Pomme avec la peau', note: 'Conserver la peau' },
        { color: 'emerald', icon: '🫐', title: 'Myrtilles / Fraises', name: 'Myrtilles / Fraises (100g)', note: '1 poignée (100g)' },
        { color: 'pink',    icon: '🥝', title: '1 Kiwi frais', name: '1 Kiwi frais', note: 'Riche en vitamine C' },
        { color: 'sky',     icon: '🍊', title: '2 Clémentines', name: '2 Clémentines / Pamplemousse', note: 'Ou 1/2 pamplemousse' },
        { color: 'purple',  icon: '🍊', title: '1 Orange', name: '1 Orange', note: 'Riche en vitamine C' },
        { color: 'indigo',  icon: '🍐', title: '1 Poire', name: '1 Poire', note: 'Fraîche & croquante' },
        { color: 'lime',    icon: '🍌', title: '1/2 Banane', name: '1/2 Banane (100g)', note: 'Pas trop mûre' },
        { color: 'rose',    icon: '🍑', title: 'Abricots ou Prunes', name: '3-4 Abricots ou Prunes', note: 'Frais de saison' },
      ]},
    ],
  },
  p2: {
    label: 'Déjeuner',
    emoji: '🍽️',
    rows: [
      { id: 'p2-1', label: 'Crudités', options: [
        { color: 'amber',   icon: '🍅', title: 'Tomates en salade', name: "Tomates fraîches + Huile d'olive", note: "1 c.à.c huile d'olive" },
        { color: 'sky',     icon: '🥕', title: 'Carottes râpées', name: 'Carottes râpées citron & colza', note: 'Citron & Huile colza' },
        { color: 'emerald', icon: '🥒', title: 'Concombre tzatziki', name: 'Concombre au yaourt & aneth', note: 'Yaourt, aneth, menthe' },
        { color: 'purple',  icon: '🥣', title: 'Soupe de légumes', name: 'Potage légumes (sans p.d.t)', note: 'Sans p.d.t (200ml)' },
        { color: 'pink',    icon: '🥬', title: 'Salade verte vinaigrette', name: 'Salade verte vinaigrette', note: 'Huile de colza' },
        { color: 'indigo',  icon: '🥗', title: 'Betteraves nature', name: 'Betteraves nature', note: 'Cuites vapeur' },
        { color: 'lime',    icon: '🥬', title: 'Radis croquants', name: 'Radis croquants', note: 'Croquants nature' },
        { color: 'rose',    icon: '🥗', title: 'Céleri rémoulade allégée', name: 'Céleri rémoulade allégée', note: 'Mayonnaise allégée' },
      ]},
      { id: 'p2-2', label: 'Protéine', options: [
        { color: 'amber',   icon: '🍗', title: 'Escalope de poulet', name: 'Escalope de poulet grillée (100g)', badge: '100-120g grillé' },
        { color: 'sky',     icon: '🐟', title: 'Pavé de saumon', name: 'Pavé de saumon au four (110g)', badge: '110g papillote' },
        { color: 'emerald', icon: '🍳', title: '2 Œufs au plat', name: '2 Œufs au plat / poêlés', badge: 'Cuits peu de gras' },
        { color: 'purple',  icon: '🥩', title: 'Steak haché 5%', name: 'Steak haché 5% poêlé (100g)', badge: '100g grillé' },
        { color: 'pink',    icon: '🍗', title: 'Escalope de dinde', name: 'Escalope de dinde (100g)', badge: '100g grillée' },
        { color: 'indigo',  icon: '🐟', title: 'Thon au naturel', name: 'Thon au naturel (100g)', badge: '100g égoutté' },
        { color: 'lime',    icon: '🦐', title: 'Crevettes décortiquées', name: 'Crevettes décortiquées (100g)', badge: '100g cuites' },
        { color: 'rose',    icon: '🍖', title: 'Jambon blanc dégraissé', name: 'Jambon blanc dégraissé (2 tranches)', badge: '2 tranches' },
      ]},
      { id: 'p2-3', label: 'Féculent', options: [
        { color: 'amber',   icon: '🍝', title: 'Pâtes complètes', name: 'Pâtes complètes (100-120g)', badge: '100-120g cuites' },
        { color: 'sky',     icon: '🍚', title: 'Riz basmati / complet', name: 'Riz basmati / complet (100g)', badge: '100g (3 c.à.s)' },
        { color: 'emerald', icon: '🫘', title: 'Lentilles vertes', name: 'Lentilles vertes (120g)', badge: '120g (4 c.à.s)' },
        { color: 'purple',  icon: '🥔', title: 'Pommes de terre', name: '2 Pommes de terre vapeur (120g)', badge: '2 petites (120g)' },
        { color: 'pink',    icon: '🍚', title: 'Semoule ou Quinoa', name: 'Semoule ou Quinoa (70g)', badge: '70g cuits' },
        { color: 'indigo',  icon: '🍞', title: 'Pain', name: 'Pain (40g)', badge: '40g' },
        { color: 'lime',    icon: '🫛', title: 'Petits pois', name: 'Petits pois (150g)', badge: '150g (8 c.à.s)' },
        { color: 'rose',    icon: '🍕', title: 'Part de Pizza ou Quiche', name: 'Part de Pizza ou Quiche (100g)', badge: '100g' },
      ]},
      { id: 'p2-4', label: 'Légumes cuits', options: [
        { color: 'amber',   icon: '🥦', title: 'Brocolis vapeur', name: "Brocolis vapeur + Huile d'olive", note: "Filet d'huile d'olive" },
        { color: 'sky',     icon: '🫛', title: 'Haricots verts', name: 'Haricots verts persillade', note: 'Persil & Ail' },
        { color: 'emerald', icon: '🍆', title: 'Ratatouille maison', name: 'Ratatouille maison', note: 'Courgettes & Poivrons' },
        { color: 'purple',  icon: '🥬', title: 'Épinards crème', name: 'Épinards à la crème 15%', note: 'Crème légère 15%' },
        { color: 'pink',    icon: '🥬', title: 'Poireaux vinaigrette', name: 'Poireaux vinaigrette', note: "Huile d'olive" },
        { color: 'indigo',  icon: '🥬', title: 'Épinards nature', name: 'Épinards nature', note: 'Vapeur' },
        { color: 'lime',    icon: '🥒', title: 'Courgettes sautées', name: 'Courgettes sautées', note: "Filet d'huile d'olive" },
        { color: 'rose',    icon: '🥦', title: 'Chou-fleur gratiné léger', name: 'Chou-fleur gratiné léger', note: 'Béchamel légère' },
      ]},
      { id: 'p2-5', label: 'Dessert', options: [
        { color: 'amber',   icon: '🧀', title: 'Portion Fromage', name: 'Fromage (30g) + pain', note: '30g + 1 bout de pain' },
        { color: 'sky',     icon: '🍍', title: 'Ananas frais', name: '2 Tranches ananas frais', note: '2 tranches fines' },
        { color: 'emerald', icon: '🥣', title: 'Fromage blanc 2%', name: 'Fromage blanc 2% sans sucre', note: '100g sans sucre' },
        { color: 'purple',  icon: '🍐', title: '1 Poire mûre', name: '1 Poire bien mûre', note: 'Riche en eau' },
        { color: 'pink',    icon: '🥛', title: 'Yaourt nature', name: 'Yaourt nature', note: 'Édulcorant si besoin' },
        { color: 'indigo',  icon: '🍏', title: 'Compote sans sucre', name: 'Compote sans sucre ajouté', note: 'Sans sucre ajouté' },
        { color: 'lime',    icon: '🥝', title: '1 Kiwi frais', name: '1 Kiwi frais', note: 'Riche en vitamine C' },
        { color: 'rose',    icon: '🥣', title: 'Petit-suisse nature', name: 'Petit-suisse nature', note: 'Nature non sucré' },
      ]},
    ],
  },
  p3: {
    label: 'Goûter',
    emoji: '🍎',
    rows: [
      { id: 'p3-1', label: 'Boisson', options: [
        { color: 'amber',   icon: '🍵', title: 'Thé vert ou Tisane', name: 'Thé vert ou Tisane', note: 'Sans sucre ajouté' },
        { color: 'pink',    icon: '🍋', title: 'Eau citronnée', name: 'Eau au citron pressé', note: '250ml rafraîchissant' },
        { color: 'emerald', icon: '☕', title: 'Décaféiné', name: 'Café décaféiné', note: 'Sans sucre' },
        { color: 'indigo',  icon: '🌿', title: 'Infusion Verveine', name: 'Infusion verveine', note: 'Apaisante sans sucre' },
        { color: 'sky',     icon: '🌿', title: 'Tisane camomille', name: 'Tisane camomille', note: 'Apaisante, sans sucre' },
        { color: 'purple',  icon: '☕', title: 'Chicorée', name: 'Chicorée', note: 'Sans caféine' },
        { color: 'lime',    icon: '💧', title: 'Eau plate', name: 'Eau plate', note: '250ml' },
        { color: 'rose',    icon: '🍵', title: 'Thé noir nature', name: 'Thé noir nature', note: 'Sans sucre' },
      ]},
      { id: 'p3-2', label: 'Fruit / Base', options: [
        { color: 'amber',   icon: '🍎', title: '1 Pomme ou Poire', name: '1 Pomme ou 1 Poire', note: 'Fraîche & croquante' },
        { color: 'pink',    icon: '🍓', title: 'Fruits rouges', name: 'Fruits rouges (1 poignée)', note: '1 poignée (100g)' },
        { color: 'emerald', icon: '🍞', title: 'Pain complet', name: '1 Tranche pain complet (30g)', note: '1 tranche (30g)' },
        { color: 'indigo',  icon: '🍌', title: '1/2 Banane', name: '1/2 Banane', note: 'Pas trop mûre' },
        { color: 'sky',     icon: '🍊', title: '1 Orange', name: '1 Orange', note: 'Riche en vitamine C' },
        { color: 'purple',  icon: '🥝', title: '2 Kiwis', name: '2 Kiwis', note: 'Riches en fibres' },
        { color: 'lime',    icon: '🍊', title: '2 Clémentines', name: '2 Clémentines', note: 'Faciles à emporter' },
        { color: 'rose',    icon: '🍑', title: '1 Pêche ou Nectarine', name: '1 Pêche ou Nectarine', note: 'Fruit de saison' },
      ]},
      { id: 'p3-3', label: 'Modérateur', options: [
        { color: 'amber',   icon: '🥜', title: 'Amandes ou Noix', name: 'Amandes / Noix non salées (15g)', badge: '15-20g (1 poignée)' },
        { color: 'pink',    icon: '🥣', title: 'Yaourt grec nature', name: 'Yaourt grec nature (1 pot)', badge: '1 pot (125g)' },
        { color: 'emerald', icon: '🧀', title: 'Portion de Comté', name: 'Comté / Cantal (30g)', badge: '30g de fromage' },
        { color: 'indigo',  icon: '🍫', title: 'Chocolat noir 70%+', name: '2 Carrés choc. noir 70% + noisettes', badge: '2 carrés + 4 noisettes' },
        { color: 'sky',     icon: '🥜', title: 'Noix de cajou non salées', name: 'Noix de cajou non salées (20g)', badge: '20g (1 poignée)' },
        { color: 'purple',  icon: '🥣', title: 'Fromage blanc 2% + amandes', name: 'Fromage blanc 2% + amandes', badge: '100g + 5 amandes' },
        { color: 'lime',    icon: '🥣', title: 'Petit-suisse nature', name: 'Petit-suisse nature (x2)', badge: '2 pots (100g)' },
        { color: 'rose',    icon: '🍫', title: 'Chocolat noir 80%', name: 'Carré de chocolat noir 80%', badge: '1 carré' },
      ]},
    ],
  },
  p4: {
    label: 'Dîner',
    emoji: '🌙',
    rows: [
      { id: 'p4-1', label: 'Légumes', options: [
        { color: 'amber',   icon: '🥣', title: 'Soupe maison', name: 'Soupe poireaux/courgettes', note: 'Poireaux & courgettes (1 bol)' },
        { color: 'sky',     icon: '🫑', title: 'Poivrons poêlés', name: 'Poivrons & courgettes poêlés', note: "Sautés à l'huile d'olive" },
        { color: 'emerald', icon: '🥗', title: 'Salade fraîcheur', name: 'Salade composée (verte, radis)', note: 'Salade verte, radis, concombre' },
        { color: 'purple',  icon: '🥦', title: 'Chou-fleur vapeur', name: 'Chou-fleur & carottes vapeur', note: 'Et carottes tendres' },
        { color: 'pink',    icon: '🫛', title: 'Haricots verts vapeur', name: 'Haricots verts vapeur', note: 'Persillade légère' },
        { color: 'indigo',  icon: '🍅', title: 'Tomates provençales', name: 'Tomates provençales', note: "Au four, sans excès d'huile" },
        { color: 'lime',    icon: '🥒', title: 'Courgettes vapeur', name: 'Courgettes vapeur', note: "Nature ou filet d'huile" },
        { color: 'rose',    icon: '🥒', title: 'Concombre en salade', name: 'Concombre en salade', note: 'Yaourt & aneth' },
      ]},
      { id: 'p4-2', label: 'Protéines', options: [
        { color: 'amber',   icon: '🍳', title: 'Omelette herbes', name: 'Omelette herbes (2 œufs)', badge: '2 œufs bio' },
        { color: 'sky',     icon: '🐟', title: 'Dos de cabillaud', name: 'Dos de cabillaud / colin (120g)', badge: '120g vapeur' },
        { color: 'emerald', icon: '🦪', title: 'Thon / Crevettes', name: 'Thon au naturel (80g) / Crevettes', badge: '80g égoutté' },
        { color: 'purple',  icon: '🧆', title: 'Tofu mariné', name: 'Tofu poêlé mariné soja (100g)', badge: '100g sauté au soja' },
        { color: 'pink',    icon: '🍗', title: 'Blanc de poulet froid', name: 'Blanc de poulet froid (100g)', badge: '100g' },
        { color: 'indigo',  icon: '🍖', title: 'Jambon blanc dégraissé', name: 'Jambon blanc dégraissé (1 tranche)', badge: '1 tranche' },
        { color: 'lime',    icon: '🧆', title: 'Tofu nature', name: 'Tofu nature (100g)', badge: '100g' },
        { color: 'rose',    icon: '🥚', title: '1 Œuf dur', name: '1 Œuf dur', badge: '1 œuf' },
      ]},
      { id: 'p4-3', label: 'Féculent', options: [
        { color: 'amber',   icon: '🍞', title: 'Pain complet', name: 'Pain complet (30-40g)', badge: '30-40g (1 tranche)' },
        { color: 'sky',     icon: '🌾', title: 'Quinoa / Boulgour', name: 'Quinoa / Boulgour cuit (80-100g)', badge: '80-100g (2-3 c.à.s)' },
        { color: 'emerald', icon: '🌽', title: 'Maïs / Pois chiches', name: 'Maïs ou Pois chiches (3 c.à.s)', badge: '3 c.à.soupe' },
        { color: 'purple',  icon: '🍜', title: 'Nouilles Soba', name: 'Nouilles Soba sarrasin (80g)', badge: '80g (sarrasin)' },
        { color: 'pink',    icon: '🍚', title: 'Riz complet', name: 'Riz complet (70g)', badge: '70g cuits' },
        { color: 'indigo',  icon: '🫘', title: 'Lentilles', name: 'Lentilles (100g)', badge: '100g' },
        { color: 'lime',    icon: '🫛', title: 'Petits pois', name: 'Petits pois (100g)', badge: '100g' },
        { color: 'rose',    icon: '🍘', title: 'Biscottes', name: 'Biscottes', badge: '2-3 biscottes' },
      ]},
      { id: 'p4-4', label: 'Laitage', options: [
        { color: 'amber',   icon: '🥛', title: 'Yaourt nature', name: 'Yaourt nature (1 pot)', note: 'Sans sucre ajouté' },
        { color: 'sky',     icon: '🥣', title: 'Faisselle 0-3%', name: 'Faisselle ciboulette (1 pot)', note: 'Pincée de ciboulette' },
        { color: 'emerald', icon: '🧀', title: 'Feta émiettée', name: 'Feta émiettée (20-30g)', note: '20-30g dans la salade' },
        { color: 'purple',  icon: '🌱', title: 'Yaourt au Soja', name: 'Yaourt au soja nature', note: 'Enrichi en calcium' },
        { color: 'pink',    icon: '🥛', title: 'Lait ribot', name: 'Lait ribot', note: 'Nature, sans sucre' },
        { color: 'indigo',  icon: '🥛', title: 'Kéfir nature', name: 'Kéfir nature', note: 'Probiotique naturel' },
        { color: 'lime',    icon: '🥣', title: 'Fromage blanc 0%', name: 'Fromage blanc 0%', note: 'Sans sucre ajouté' },
        { color: 'rose',    icon: '🧀', title: 'Mozzarella light', name: 'Mozzarella light (20g)', note: '20g' },
      ]},
      { id: 'p4-5', label: 'Fruit / Douceur', options: [
        { color: 'amber',   icon: '🍏', title: 'Compote maison', name: 'Compote maison sans sucre', note: 'Sans sucre ajouté' },
        { color: 'sky',     icon: '🍑', title: '1 Pêche / Nectarine', name: '1 Pêche ou Nectarine', note: 'Fruit frais de saison' },
        { color: 'emerald', icon: '🍊', title: '1 Orange fraîche', name: '1 Orange en quartiers', note: 'En quartiers' },
        { color: 'purple',  icon: '🍈', title: 'Tranche de melon', name: '1 Tranche de melon (120g)', note: '120g rafraîchissant' },
        { color: 'pink',    icon: '🍎', title: '1 Pomme', name: '1 Pomme', note: 'Avec la peau' },
        { color: 'indigo',  icon: '🍐', title: '1 Poire', name: '1 Poire', note: 'Bien mûre' },
        { color: 'lime',    icon: '🍇', title: 'Raisin', name: '100g de Raisin', note: 'Une quinzaine de grains' },
        { color: 'rose',    icon: '🍇', title: '2 Figues fraîches', name: '2 Figues fraîches (100g)', note: '100g' },
      ]},
    ],
  },
};
